@MvcRatings_Host_Address = http://localhost:5161

###USER:
POST {{MvcRatings_Host_Address}}/api/User
Content-Type: application/json
Accept: application/json

{
  "FirstName": "Witold",
  "LastName": "Tacikiewicz"
}
###
GET {{MvcRatings_Host_Address}}/api/User
Accept: application/json
###
DELETE {{MvcRatings_Host_Address}}/api/User/5
Accept: application/json
###
PUT {{MvcRatings_Host_Address}}/api/User/4
Content-Type: application/json
Accept: application/json

{
  "Id": 4,
  "FirstName": "Jan",
  "LastName": "Ciasto"
}




###ARTIST:
POST {{MvcRatings_Host_Address}}/api/Artist
Content-Type: application/json
Accept: application/json

{
  "Name": "Chief Keef",
  "Bio": "Sosa! O-Block! Bang bang!"
}
###
GET {{MvcRatings_Host_Address}}/api/Artist
Accept: application/json
###
DELETE {{MvcRatings_Host_Address}}/api/Artist/7
Accept: application/json
###
PUT {{MvcRatings_Host_Address}}/api/Artist/1
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Name": "Kendrick Lamar",
  "Bio": "Baby Keem's cousin"
}





###ALBUM:
POST {{MvcRatings_Host_Address}}/api/Album
Content-Type: application/json
Accept: application/json

{
  "Title": "Almighty So 2",
  "ArtistId": 5,
  "ReleaseDate": "2024-05-10"
}
###
GET {{MvcRatings_Host_Address}}/api/Album
Accept: application/json
###
DELETE {{MvcRatings_Host_Address}}/api/Album/9
Accept: application/json
###
PUT {{MvcRatings_Host_Address}}/api/Album/1
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Title": "To Pimp a Butterfly",
  "ArtistId": 1,
  "ReleaseDate": "2015-03-15"
}





###SONG:
POST {{MvcRatings_Host_Address}}/api/Song
Content-Type: application/json
Accept: application/json

{
  "Title": "Hate Bein' Sober",
  "ArtistId": 5,
  "AlbumId": 8,
  "ReleaseDate": "2012-12-18",
  "Duration": "00:04:40"
}
###
GET {{MvcRatings_Host_Address}}/api/Song
Accept: application/json
###
DELETE {{MvcRatings_Host_Address}}/api/Song/1
Accept: application/json
###
PUT {{MvcRatings_Host_Address}}/api/Song/1
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Title": "Song 1",
  "ArtistId": 1,
  "AlbumId": 1,
  "ReleaseDate": "2021-01-01",
  "Duration": "00:03:30"
}



###RATING:
POST {{MvcRatings_Host_Address}}/api/Rating
Content-Type: application/json
Accept: application/json

{
  "UserId": 4,
  "SongId": 22,
  "Value": 3,
  "Date": "2022-12-05",
  "Comment":  "random review boring"
}
###
GET {{MvcRatings_Host_Address}}/api/Rating
Accept: application/json
###
DELETE {{MvcRatings_Host_Address}}/api/Rating/1
Accept: application/json
###
PUT {{MvcRatings_Host_Address}}/api/Rating/1
Content-Type: application/json
Accept: application/json

{
  "Id": 1,
  "Value": 1,
  "UserId": 1,
  "SongId": 1,
  "Date": "2022-03-01",
  "Comment": "Great song whoah!"
}